package loblaw.image.compare.helper.format;

/**
 * @author Mohit Kumar
 * Description: This class is a custom format of output generated by processing the input file
 */
public class ImageProcessOuput {
	/**
	 * Variable to store custom error messages
	 */
	private String error;
	/**
	 * Variable to store custom output file path
	 */
	private String outputFile;
	
	/**
	 * Constructor
	 * @param error
	 * @param outputFile
	 */
	public ImageProcessOuput(String error, String outputFile) {
		super();
		this.error = error;
		this.outputFile = outputFile;
	}
	/**
	 * @return the error
	 */
	public String getError() {
		return error;
	}
	/**
	 * @param error the error to set
	 */
	public void setError(String error) {
		this.error = error;
	}
	/**
	 * @return the outputFile
	 */
	public String getOutputFile() {
		return outputFile;
	}
	/**
	 * @param outputFile the outputFile to set
	 */
	public void setOutputFile(String outputFile) {
		this.outputFile = outputFile;
	}

}
